# Generated by Django 5.2.7 on 2025-10-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('codigo', models.CharField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
    ]
