# Generated by Django 5.2.7 on 2025-10-31 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plataforma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('dni', models.CharField(primary_key=True, serialize=False)),
                ('contra', models.CharField(max_length=18)),
            ],
        ),
    ]
