# Generated by Django 5.2.7 on 2025-11-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plataforma', '0002_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='nombre',
        ),
        migrations.AddField(
            model_name='turno',
            name='dni',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
